const LOAD = {
  "pattern": "UTTT TTTU UTUT UUUU",
  "date": "16.12.23",
  "dictionary": {
    "HH": "п",
    "HC": "р",
    "IK": "о",
    "GF": "т",
    "IO": "и",
    "FH": "в",
    "JA": "н",
    "ON": "к",
    "AN": "а",
    "BM": "<EMPTY>",
    "GH": "7",
    "DD": "г",
    "OO": "у",
    "AA": " ",
    "NB": "ж",
    "EM": "е",
    "PJ": "ю",
    "CK": "ч",
    "MF": "ы",
    "KC": "х",
    "CM": "с",
    "NO": "д",
    "KK": "б",
    "KO": "о",
    "PD": "л",
    "HD": "м",
    "AF": "з",
    "NF": "ь",
    "CC": "ф",
    "KJ": "к",
    "EO": "в",
    "MB": "с",
    "CP": "ц",
    "BE": "я",
    "ED": "щ",
    "JE": ",",
    "FN": "з",
    "FP": "т",
    "OE": "ш",
    "EI": "й",
    "HN": "б",
    "LM": "(",
    "EC": ")",
    "GN": ".",
    "DL": "-",
    "CF": "(",
    "HM": ")",
    "LA": "п",
    "DC": "1",
    "FO": "9",
    "KB": "4",
    "GA": "3",
    "AJ": "0",
    "OP": "<img src=\"prikol.png\" width=20 height=20>"
  }
}